blank_issues_enabled: true
contact_links:
  - name: Silverbullet Documentation
    url: https://silverbullet.md
    about: Official Silverbullet documentation
  - name: Discussions
    url: https://github.com/silverbulletmd/silverbullet/discussions
    about: Silverbullet community discussions
